##################################################
## Binary Sensors
##################################################
- platform: template
  sensors:
    ensuite_shower_active:
      friendly_name: "Ensuite Shower Active"
      value_template: "{{ states('sensor.ensuite_shower_power2') | float > 4.0 }}"
      delay_on:
        seconds: 20
      delay_off:
        seconds: 20
    family_bathroom_shower_active:
      friendly_name: "Familiy Bathroom Shower Active"
      value_template: "{{ states('sensor.family_bathroom_shower_power') | float > 4.0 }}"
      delay_on:
        seconds: 20
      delay_off:
        seconds: 20
# Ping Fraser TV every 5 mins to see if it's on.
- platform: ping
  host: 192.168.200.75
  name: "Frasers TV"
  count: 2

# Sensor to detect if Fraser PC has been idle for over 5 mins
- platform: template
  sensors:
    tera_pc_idle:
      friendly_name: "Frasers PC On but Idle"
      value_template: "{{as_timestamp(states.sensor.lastactive.last_changed) < as_timestamp(now()) - 300}}"
