###################################################
#     Home Assistant Main Configuration File      #
###################################################
homeassistant:
  customize: !include customize.yaml
  # https://home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages
  # Allow access to config dir, in order to have a sensor to monitor DB size.
  allowlist_external_dirs:
    - !secret allow_dir

# Include Files
automation: !include automations.yaml
group: !include groups.yaml
input_boolean: !include input_booleans.yaml
light: !include lights.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

####################################################
#            Home Assistant Components             #
####################################################
# https://www.home-assistant.io/integrations/api/
api:
# https://www.home-assistant.io/integrations/default_config/
default_config:
# https://www.home-assistant.io/integrations/history
history:

# https://www.home-assistant.io/components/logbook/
logbook:
  include:
    domains:
      - automation
      - script
# https://www.home-assistant.io/components/logger/
logger:
  default: warning
  # logs:
    # homeassistant.core: debug
    # homeassistant.components.recorder.core: debug
    # RFXtrx: debug
# https://www.home-assistant.io/docs/ecosystem/ios/
ios:
# https://www.home-assistant.io/components/recorder/
recorder:

# https://www.home-assistant.io/components/sun/
sun:
            
##################################################
#                   Templates                    #
##################################################
template:
- sensor:
  - default_entity_id: sensor.sun_template
    unique_id: sun_template
    icon: '{% if is_state(''sun.sun'', ''above_horizon'') %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'
    name: Sun
    state: '{{ as_timestamp(states.sun.sun.attributes.next_rising) |  timestamp_custom(''%H:%M'', True) }} • {{ as_timestamp(states.sun.sun.attributes.next_setting) |  timestamp_custom(''%H:%M'', True) }}'
