####################################################
#                Template Sensors                  #
####################################################
- platform: template
  sensors:
    sun_template:
      friendly_name: "Sun"
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) |  timestamp_custom('%H:%M', True) }} • {{ as_timestamp(states.sun.sun.attributes.next_setting) |  timestamp_custom('%H:%M', True) }}"
      icon_template: "{% if is_state('sun.sun', 'above_horizon') %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}"

# Tera PC State
    tera_powered_on:
      friendly_name: "PC Tera Powered On"
      value_template: "{{ not(is_state('switch.shutdown', 'unavailable')) }}"

####################################################
#                Component Sensors                 #
####################################################


###################################################
#               History Statistics                 #
####################################################
- platform: history_stats
  name: Ensuite Shower Uses Today
  entity_id: binary_sensor.ensuite_shower_active
  type: count
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Family Bathroom Shower Uses Today
  entity_id: binary_sensor.family_bathroom_shower_active
  type: count
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Ensuite Shower Time Today
  entity_id: binary_sensor.ensuite_shower_active
  type: time
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Family Bathroom Shower Time Today
  entity_id: binary_sensor.family_bathroom_shower_active
  type: time
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
  