####################################################
#                Template Sensors                  #
####################################################
- platform: template
  sensors:
    sun_template:
      friendly_name: "Sun"
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) |  timestamp_custom('%H:%M', True) }} • {{ as_timestamp(states.sun.sun.attributes.next_setting) |  timestamp_custom('%H:%M', True) }}"
      icon_template: "{% if is_state('sun.sun', 'above_horizon') %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}"

# WH5 Portable Temperature and Humidity Sensors
    portable_sensor_1_temperature:
      value_template: "{{ (states('sensor.temp_humid_1_temperature') | float - 40) | round(1) }}"
      unit_of_measurement: '°C'
      friendly_name: "Temperature (Conservatory)"
    portable_sensor_2_temperature:
      value_template: "{{ (states('sensor.temp_humid_2_temperature') | float - 40) | round(1) }}"
      unit_of_measurement: '°C'
      friendly_name: "Temperature (Living Room)"
    portable_sensor_3_temperature:
      value_template: "{{ (states('sensor.temp_humid_3_temperature') | float - 40) | round(1) }}"
      unit_of_measurement: '°C'
      friendly_name: "Temperature (Fraser)"
    portable_sensor_5_temperature:
      value_template: "{{ (states('sensor.temp_humid_5_temperature') | float - 40) | round(1) }}"
      unit_of_measurement: '°C'
      friendly_name: "Temperature (Morgan)"

# Tera PC State
    tera_powered_on:
      friendly_name: "PC Tera Powered On"
      value_template: "{{ not(is_state('switch.shutdown', 'unavailable')) }}"


####################################################
#                  Command Line                    #
####################################################
# Pi Temperature
- platform: command_line
  name: HA CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

####################################################
#                Component Sensors                 #
####################################################
# Raspberry Pi System Information
- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: swap_use_percent
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m

# Owl Energy Monitor
- platform: owlintuition
  host: 192.168.200.45
  port: 32000
  mode: triphase
  cost_icon: 'mdi:currency-gbp'
  cost_unit_of_measurement: GBP
  monitored_conditions:
    - electricity
    - solar

# REST Sensors - https://www.home-assistant.io/integrations/sensor.rest/
# - platform: rest
#   resource: http://localhost:8123/homeassistant/api/states/sensor.argon_one_addon_fan_speed
#   method: POST
#   payload: {}

####################################################
#               History Statistics                 #
####################################################
- platform: history_stats
  name: Ensuite Shower Uses Today
  entity_id: binary_sensor.ensuite_shower_active
  type: count
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Family Bathroom Shower Uses Today
  entity_id: binary_sensor.family_bathroom_shower_active
  type: count
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Ensuite Shower Time Today
  entity_id: binary_sensor.ensuite_shower_active
  type: time
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Family Bathroom Shower Time Today
  entity_id: binary_sensor.family_bathroom_shower_active
  type: time
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
