##################################################
## Customize
##################################################
homeassistant:
  customize:
    sensor.ironing_room_motion_status:
      icon: mdi-motion-sensor
    sensor.laurastar_iron_power:
      icon: mdi:flash
    sensor.laurastar_iron_power_today:
      icon: mdi:counter
    sensor.irons_left_power:
      icon: mdi:flash
    sensor.irons_left_power_today:
      icon: mdi:counter
    sensor.irons_right_power:
      icon: mdi:flash
    sensor.irons_right_power_today:
      icon: mdi:counter
    sensor.ironing_table_power:
      icon: mdi:flash
    sensor.ironing_table_power_today:
      icon: mdi:counter
    sensor.magpie_iron_power:
      icon: mdi:flash
    sensor.magpie_iron_power_today:
      icon: mdi:counter
    sensor.ironing_room_total_power_now:
      icon: mdi:flash
    sensor.ironing_room_total_power_today:
      icon: mdi:counter
    sensor.ironing_room_power_cost_today:
      icon: mdi:currency-gbp

##################################################
## Components/Sensors
##################################################
input_select:
  ironing_room_motion_status:
    name: Ironing Room Motion Status
    options:
      - idle
      - motion
    initial: motion

tplink:
  switch:
    - host: 192.168.200.21 # DHCP reservation
    - host: 192.168.200.22 # DHCP reservation
    - host: 192.168.200.23 # DHCP reservation
    - host: 192.168.200.24 # DHCP reservation
    - host: 192.168.200.25 # DHCP reservation

sensor:
  - platform: template
    sensors:
      # TP-Link HS110 Power Sockets Power Usage
      laurastar_iron_power:
        value_template: "{{ states.switch.laurastar_iron.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Laurastar Iron"
      laurastar_iron_power_today:
        value_template: "{{ states.switch.laurastar_iron.attributes['today_energy_kwh'] | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Laurastar Iron"
      irons_left_power:
        value_template: "{{ states.switch.irons_left.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Ironing Room Left"
      irons_left_power_today:
        value_template: "{{ states.switch.irons_left.attributes['today_energy_kwh'] | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Room Left"
      irons_right_power:
        value_template: "{{ states.switch.irons_right.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Ironing Room Right"
      irons_right_power_today:
        value_template: "{{ states.switch.irons_right.attributes['today_energy_kwh'] | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Room Right"
      ironing_table_power:
        value_template: "{{ states.switch.ironing_table.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Ironing Table"
      ironing_table_power_today:
        value_template: "{{ states.switch.ironing_table.attributes['today_energy_kwh'] | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Table"
      magpie_iron_power:
        value_template: "{{ states.switch.magpie_iron.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Power - Magpie Iron"
      magpie_iron_power_today:
        value_template: "{{ states.switch.magpie_iron.attributes['today_energy_kwh'] | float | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Magpie Iron"
      ironing_room_total_power_now:
        value_template: "{{ (states('sensor.laurastar_iron_power') | float + states('sensor.irons_left_power') | float + states('sensor.irons_right_power') | float + states('sensor.ironing_table_power') | float + states('sensor.magpie_iron_power') | float) | round(3) }}"
        unit_of_measurement: 'W'
        friendly_name: "Power Now - Ironing Room"
      ironing_room_total_power_today:
        value_template: "{{ (states('sensor.laurastar_iron_power_today') | float + states('sensor.irons_left_power_today') | float + states('sensor.irons_right_power_today') | float + states('sensor.ironing_table_power_today') | float + states('sensor.magpie_iron_power_today') | float) | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Room"
      ironing_room_power_cost_today:
        value_template: "{{ (states('sensor.ironing_room_total_power_today') |float * 0.10624 ) | round(2) }}"
        unit_of_measurement: 'GBP'
        friendly_name: "Power Cost Today - Ironing Room"
      ironing_room_motion_status: 
        value_template: "{{ states.input_select.ironing_room_motion_status.state }}"
        friendly_name: "Ironing Room Motion Status"

##################################################
## Automation
##################################################
automation:
# When we detect motion, set status to Motion
  - alias: Ironing room motion detected
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_ironing_room
        to: 'on'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.ironing_room_motion_status
          option: 'motion'

# No Motion for 30 minutes, set to idle
  - alias: Ironing room no motion 30 mins
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_ironing_room
        to: 'off'
        for:
          minutes: 30
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.ironing_room_motion_status
          option: 'idle'

# Switch off if drawing power and no motion in pending state
  - alias: Ironing Room No Motion Turn off Irons Left
    trigger:
      - platform: numeric_state
        entity_id: sensor.irons_left_power
        above: 10
        for: 
          seconds: 10
    condition:
      - condition: state
        entity_id: sensor.ironing_room_motion_status
        state: 'idle'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.irons_left
      - service: notify.michelle
        data:
          title: "Ironing Room Alert!"
          message: "No Motion Detected - Turning off Ironing room Irons (Left)"

  - alias: Ironing Room No Motion Turn off Irons Right
    trigger:
      - platform: numeric_state
        entity_id: sensor.irons_right_power
        above: 10
        for:
          seconds: 10
    condition:
      - condition: state
        entity_id: input_select.ironing_room_motion_status
        state: 'idle'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.irons_right
      - service: notify.michelle
        data:
          title: "Ironing Room Alert!"
          message: "No Motion Detected - Turning off Ironing room Irons (Right)"

  - alias: Ironing Room No Motion Turn off Ironing Table
    trigger:
      - platform: numeric_state
        entity_id: sensor.ironing_table_power
        above: 10
        for:
          seconds: 10
    condition:
      - condition: state
        entity_id: input_select.ironing_room_motion_status
        state: 'idle'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.ironing_table
      - service: notify.michelle
        data:
          title: "Ironing Room Alert!"
          message: "No Motion Detected - Turning off Ironing Table"

  - alias: Ironing Room No Motion Turn off Magpie Iron
    trigger:
      - platform: numeric_state
        entity_id: sensor.magpie_iron_power
        above: 10
        for: 
          seconds: 10
    condition:
      - condition: state
        entity_id: input_select.ironing_room_motion_status
        state: 'idle'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.magpie_iron
      - service: notify.michelle
        data:
          title: "Ironing Room Alert!"
          message: "No Motion Detected - Turning off Magpie Iron"

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.ironing_room_motion_status
      - sensor.ironing_room_motion
      - sensor.laurastar_iron_power
      - sensor.laurastar_iron_power_today
      - sensor.irons_left_power
      - sensor.irons_left_power_today
      - sensor.irons_right_power
      - sensor.irons_right_power_today
      - sensor.ironing_table_power
      - sensor.ironing_table_power_today
      - sensor.magpie_iron_power
      - sensor.magpie_iron_power_today
      - sensor.ironing_room_total_power_now
      - sensor.ironing_room_total_power_today
      - sensor.ironing_room_power_cost_today

history:
  include:
    entities:
      - sensor.ironing_room_motion_status
      - sensor.ironing_room_motion
      - sensor.laurastar_iron_power
      - sensor.laurastar_iron_power_today
      - sensor.irons_left_power
      - sensor.irons_left_power_today
      - sensor.irons_right_power
      - sensor.irons_right_power_today
      - sensor.ironing_table_power
      - sensor.ironing_table_power_today
      - sensor.magpie_iron_power
      - sensor.magpie_iron_power_today
      - sensor.ironing_room_total_power_now
      - sensor.ironing_room_total_power_today
      - sensor.ironing_room_power_cost_today
