##################################################
## Customize
##################################################
homeassistant:
  customize:
    switch.washing_machine:
      friendly_name: "Washing Machine"
      icon: mdi:washing-machine

##################################################
## Components/Sensors
##################################################
tplink:
  switch:
    - host: 192.168.200.27 # DHCP reservation

input_select:
  washing_machine_status:
    name: Washing Machine Status
    options:
      - idle
      - running
      - finished
    initial: idle

sensor:
  - platform: template
    sensors:
      washing_machine_power:
        value_template: "{{ states.switch.washing_machine.attributes['current_power_w'].split(' ')[0] }}"
        unit_of_measurement: 'W'
        friendly_name: "Washing Machine Power"
      washing_machine_power_today:
        value_template: "{{ states.switch.washing_machine.attributes['today_energy_kwh'] | float | round(2) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Washing Machine Power Today"
  - platform: template
    sensors:
      washing_machine_status:
        value_template: "{{ states.input_select.washing_machine_status.state }}"
        friendly_name: "Washing Machine Status"

  - platform: history_stats
    name: Washing machine uses today
    entity_id: sensor.washing_machine_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Washing machine uses this week
    entity_id: sensor.washing_machine_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'


##################################################
## Automation
##################################################
automation:
# When we detect power being drawn from the washing machine, above 5W,
# mark the washing machine as using started
  - alias: Set washing machine active when power detected
    trigger:
      - platform: numeric_state
        entity_id: sensor.washing_machine_power
        above: 5
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: 'idle'
        - condition: state
          entity_id: input_select.washing_machine_status
          state: 'finished'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: 'running'

# When the power level drops below 5W, for 2 minutes and the washing machine is set to
# the 'running' state, mark the washing machine as Finished and send notification.
  - alias: Set washing machine to finished when power drops
    trigger:
      - platform: numeric_state
        entity_id: sensor.washing_machine_power
        below: 5
        for:
          minutes: 2
    condition:
      condition: state
      entity_id: input_select.washing_machine_status
      state: 'running'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: 'finished'
      - service: notify.michelle
        data:
          message: "Finished!"
          title: "Washing Machine"

# Once the washing machine status has been 'finished' for 2 minutes, mark the
# washing machine as idle
  - alias: Set Washing Machine to idle
    trigger:
      - platform: state
        entity_id: input_select.washing_machine_status
        to: 'finished'
        for:
          minutes: 2
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: 'idle'

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.washing_machine_status
      - sensor.washing_machine_power
      - sensor.washing_machine_power_today

history:
  include:
    entities:
      - sensor.washing_machine_status
      - sensor.washing_machine_power
      - sensor.washing_machine_power_today