####################################################
#             HACS: Custom Components              #
####################################################
# https://github.com/USA-RedDragon/badnest
badnest:
  user_id: !secret badnest_userid
  access_token: !secret badnest_token
  region: eu

##################################################
## Components/Sensors
##################################################
climate:
  - platform: badnest
    scan_interval: 10

sensor:
  - platform: template
    sensors:
      hot_water_boost_status:
        friendly_name: "Hot Water Boost Status"
        value_template: "{{ state_attr('water_heater.hallway_thermostat_hot_water', 'boost_mode_status') }}"

water_heater:
  - platform: badnest

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.hot_water_tank_temperature
      - sensor.hot_water_boost_status
      - water_heater.hallway_thermostat_hot_water

history:
  include:
    entities:
      - sensor.hot_water_tank_temperature
      - sensor.hot_water_boost_status
      - water_heater.hallway_thermostat_hot_water
