homeassistant:
  customize_glob:
    sensor.server_glance*:
      icon: mdi:check
  customize:
    sensor.server_server_power_state:
      icon: mdi:power
    sensor.server_cpu_fanspeed:
      icon: mdi:fan
    sensor.server_server_name:
      icon: mdi:server-network
    sensor.server_server_health:
      hidden: true

sensor:
  # - platform: hp_ilo
  #   name: Nano
  #   host: !secret hp_ilo_server
  #   port: 443
  #   username: !secret hp_ilo_username
  #   password: !secret hp_ilo_password
  #   monitored_variables:
  #     - name: Server name
  #       sensor_type: server_name
  #     - name: Server Health
  #       sensor_type: server_health
  #     - name: CPU fanspeed
  #       sensor_type: server_health
  #       unit_of_measurement: '%'
  #       value_template: '{{ ilo_data.fans["Fan 1"].speed[0] }}'
  #     - name: Inlet temperature
  #       sensor_type: server_health
  #       unit_of_measurement: '°C'
  #       value_template: '{{ ilo_data.temperature["01-Inlet Ambient"].currentreading[0] }}'
  #     - name: Exhaust temperature
  #       sensor_type: server_health
  #       unit_of_measurement: '°C'
  #       value_template: '{{ ilo_data.temperature["12-Sys Exhaust"].currentreading[0] }}'
  #     - name: CPU temperature
  #       sensor_type: server_health
  #       unit_of_measurement: '°C'
  #       value_template: '{{ ilo_data.temperature["02-CPU"].currentreading[0] }}'
  #     - name: Chipset temperature
  #       sensor_type: server_health
  #       unit_of_measurement: '°C'
  #       value_template: '{{ ilo_data.temperature["05-Chipset"].currentreading[0] }}'
  #     - name: Memory temperature
  #       sensor_type: server_health
  #       unit_of_measurement: '°C'
  #       value_template: '{{ ilo_data.temperature["03-P1 DIMM 1-2"].currentreading[0] }}'
  #     - name: PCI Temperature
  #       sensor_type: server_health
  #       unit_of_measurement: '°C'
  #       value_template: '{{ ilo_data.temperature["10-PCI 1"].currentreading[0] }}'
  #     - name: Glance Power Supplies
  #       sensor_type: server_health
  #       value_template: '{{ ilo_data.health_at_a_glance["power_supplies"]["status"] }}'
  #     - name: Glance Processor
  #       sensor_type: server_health
  #       value_template: '{{ ilo_data.health_at_a_glance["processor"]["status"] }}'
  #     - name: Glance Storage
  #       sensor_type: server_health
  #       value_template: '{{ ilo_data.health_at_a_glance["storage"]["status"] }}'      
  #     - name: Glance Memory
  #       sensor_type: server_health
  #       value_template: '{{ ilo_data.health_at_a_glance["memory"]["status"] }}'
  #     - name: Glance Temperatures  
  #       sensor_type: server_health
  #       value_template: '{{ ilo_data.health_at_a_glance["temperature"]["status"] }}'
  #     - name: Glance Fans
  #       sensor_type: server_health
  #       value_template: '{{ ilo_data.health_at_a_glance["fans"]["status"] }}'
  #     - name: Glance Network
  #       sensor_type: server_health
  #       value_template: '{{ ilo_data.health_at_a_glance["network"]["status"] }}'
  #     - name: Glance bios
  #       sensor_type: server_health
  #       value_template: '{{ ilo_data.health_at_a_glance["bios_hardware"]["status"] }}'
