##################################################
## Components/Sensors
##################################################
tplink:
  switch:
    - host: 192.168.170.20 # DHCP reservation - KP115_2 - Irons Left
    - host: 192.168.170.23 # DHCP reservation - HS110_3 - Irons Right
    - host: 192.168.170.24 # DHCP reservation - HS110_4 - Table
    - host: 192.168.170.29 # DCHP reservation - KP115_1 - Magpie Iron

sensor:
  - platform: template
    sensors:
      ironing_room_total_power_now:
        value_template: "{{ (states('sensor.irons_left_2_current_consumption') | float + states('sensor.irons_right_current_consumption') | float + states('sensor.ironing_table_current_consumption') | float + states('sensor.magpie2_current_consumption') | float) | round(3) }}"
        unit_of_measurement: 'W'
        friendly_name: "Power Now - Ironing Room"
      ironing_room_total_power_today:
        value_template: "{{ (states('sensor.irons_left_2_today_s_consumption') | float + states('sensor.irons_right_today_s_consumption') | float + states('sensor.ironing_table_today_s_consumption') | float + states('sensor.magpie2_today_s_consumption') | float) | round(3) }}"
        unit_of_measurement: 'kWh'
        friendly_name: "Power Today - Ironing Room"
      ironing_room_power_cost_today:
        value_template: "{{ (states('sensor.ironing_room_total_power_today') |float * 0.17902 ) | round(2) }}"
        unit_of_measurement: 'GBP'
        friendly_name: "Power Cost Today - Ironing Room"
      ironing_room_motion_status: 
        value_template: "{{ states.input_select.ironing_room_motion_status.state }}"
        friendly_name: "Ironing Room Motion Status"
