##################################################
## Components/Sensors
##################################################
input_select:
  ironing_room_motion_status:
    name: Ironing Room Motion Status
    options:
      - idle
      - motion
    initial: motion

homeassistant:
  customize:
    sensor.ironing_room_motion_status:
      icon: mdi:motion-sensor
    sensor.ironing_room_total_power_today:
      icon: mdi:counter
    sensor.ironing_room_power_cost_today:
      icon: mdi:currency-gbp
    binary_sensor.lumi_lumi_sensor_magnet_aq2_10327502_on_off:
      friendly_name: Ironing Room - Window
      icon: mdi:window-open
    binary_sensor.motion_sensor_ironing_room:
      icon: mdi:motion-sensor

template:
- sensor:
  - unit_of_measurement: W
    default_entity_id: sensor.ironing_room_total_power_now
    unique_id: ironing_room_total_power_now
    device_class: power
    state_class: measurement
    name: Power Now - Ironing Room
    availability: >
      {{ has_value('sensor.ironing_room_left_current_consumption') and
         has_value('sensor.ironing_room_right_current_consumption') and
         has_value('sensor.ironing_room_ironing_table_current_consumption') and
         has_value('sensor.ironing_room_magpie_current_consumption') }}
    state: >
      {{ (
        states('sensor.ironing_room_left_current_consumption') | float(0) +
        states('sensor.ironing_room_right_current_consumption') | float(0) +
        states('sensor.ironing_room_ironing_table_current_consumption') | float(0) +
        states('sensor.ironing_room_magpie_current_consumption') | float(0)
      ) | round(3) }}
- sensor:
  - unit_of_measurement: kWh
    default_entity_id: sensor.ironing_room_total_power_today
    unique_id: ironing_room_total_power_today
    device_class: energy
    state_class: total_increasing
    name: Power Today - Ironing Room
    availability: >
      {{ has_value('sensor.ironing_room_left_today_s_consumption') and
         has_value('sensor.ironing_room_right_today_s_consumption') and
         has_value('sensor.ironing_room_ironing_table_today_s_consumption') and
         has_value('sensor.ironing_room_magpie_today_s_consumption') }}
    state: >
      {{ (
        states('sensor.ironing_room_left_today_s_consumption') | float(0) +
        states('sensor.ironing_room_right_today_s_consumption') | float(0) +
        states('sensor.ironing_room_ironing_table_today_s_consumption') | float(0) +
        states('sensor.ironing_room_magpie_today_s_consumption') | float(0)
      ) | round(3) }}
- sensor:
  - unit_of_measurement: GBP
    default_entity_id: sensor.ironing_room_power_cost_today
    unique_id: ironing_room_power_cost_today
    device_class: monetary
    state_class: total
    name: Power Cost Today - Ironing Room
    availability: >
      {{ has_value('sensor.electricity_unit_price') and
         has_value('sensor.ironing_room_total_power_today') }}
    state: >
      {{ (
        states('sensor.electricity_unit_price') | float(0) *
        states('sensor.ironing_room_total_power_today') | float(0)
      ) | round(4) }}
- sensor:
  - default_entity_id: sensor.ironing_room_motion_status
    unique_id: ironing_room_motion_status
    name: Ironing Room Motion Status
    availability: "{{ has_value('input_select.ironing_room_motion_status') }}"
    state: "{{ states('input_select.ironing_room_motion_status') }}"
