##################################################
## Components/Sensors
##################################################
template:
- sensor:
  - default_entity_id: sensor.dishwasher_status
    name: Dishwasher Status
    state: '{{ states(''input_select.dishwasher_status'') }}'
- sensor:
  - default_entity_id: sensor.dryer_status
    name: Tumble Dryer Status
    state: '{{ states(''input_select.dryer_status'') }}'
- sensor:
  - default_entity_id: sensor.washing_machine_status
    name: Washing Machine Status
    state: '{{ states(''input_select.washing_machine_status'') }}'
- sensor:
  - unit_of_measurement: W
    default_entity_id: sensor.kitchen_total_power_now
    name: Power Now - Kitchen
    state: '{{ (states(''sensor.dishwasher_current_consumption'') | float + states(''sensor.tumble_dryer_current_consumption'')
      | float + states(''sensor.washing_machine_current_consumption'') | float) |
      round(3) }}'
- sensor:
  - unit_of_measurement: kWh
    default_entity_id: sensor.kitchen_total_power_today
    name: Power Today - Kitchen
    state: '{{ (states(''sensor.dishwasher_today_s_consumption'') | float + states(''sensor.tumble_dryer_today_s_consumption'')
      | float + states(''sensor.washing_machine_today_s_consumption'') | float) |
      round(3) }}'
- sensor:
  - unit_of_measurement: GBP
    default_entity_id: sensor.dishwasher_total_power_cost_today
    name: Dishwasher Cost Today
    state: '{{ (states(''input_number.energy_elec_unit'') | float * states(''sensor.dishwasher_today_s_consumption'')
      | float) | round(2) }}'
- sensor:
  - unit_of_measurement: GBP
    default_entity_id: sensor.tumble_dryer_total_power_cost_today
    name: Tumble Dryer Cost Today
    state: '{{ (states(''input_number.energy_elec_unit'') | float * states(''sensor.tumble_dryer_today_s_consumption'')
      | float) | round(2) }}'      
- sensor:
  - unit_of_measurement: GBP
    default_entity_id: sensor.washing_machine_total_power_cost_today
    name: Washing Machine Cost Today
    state: '{{ (states(''input_number.energy_elec_unit'') | float * states(''sensor.washing_machine_today_s_consumption'')
      | float) | round(2) }}'
- sensor:
  - unit_of_measurement: GBP
    default_entity_id: sensor.kitchen_total_power_cost_today
    name: Power Cost Today - Kitchen
    state: '{{ (states(''input_number.energy_elec_unit'') | float * states(''sensor.kitchen_total_power_today'')
      | float) | round(2) }}'

sensor:
  - platform: history_stats
    name: Dishwasher uses today
    entity_id: sensor.dishwasher_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Dishwasher uses this week
    entity_id: sensor.dishwasher_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Dryer uses today
    entity_id: sensor.dryer_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Dryer uses this week
    entity_id: sensor.dryer_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Washing machine uses today
    entity_id: sensor.washing_machine_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Washing machine uses this week
    entity_id: sensor.washing_machine_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
