##################################################
## Components/Sensors
##################################################
input_select:
  dishwasher_status:
    name: Dishwasher Status
    options:
      - idle
      - running
      - finished
    initial: idle
  washing_machine_status:
    name: Washing Machine Status
    options:
      - idle
      - running
      - finished
    initial: idle
  dryer_status:
    name: Tumble Dryer Status
    options:
      - idle
      - running
      - finished
    initial: idle

homeassistant:
  customize:
    sensor.washing_machine_status:
      icon: mdi:state-machine
    sensor.kitchen_total_power_now:
      icon: mdi:flash
    sensor.kitchen_total_power_today:
      icon: mdi:counter
    sensor.kitchen_total_power_cost_today:
      icon: mdi:currency-gbp
    sensor.dryer_status:
      icon: mdi:state-machine
    sensor.dishwasher_status:
      icon: mdi:state-machine

template:
- sensor:
  - default_entity_id: sensor.dishwasher_status
    unique_id: dishwasher_status
    name: Dishwasher Status
    availability: "{{ has_value('input_select.dishwasher_status') }}"
    state: '{{ states(''input_select.dishwasher_status'') }}'
- sensor:
  - default_entity_id: sensor.dryer_status
    unique_id: dryer_status
    name: Tumble Dryer Status
    availability: "{{ has_value('input_select.dryer_status') }}"
    state: '{{ states(''input_select.dryer_status'') }}'
- sensor:
  - default_entity_id: sensor.washing_machine_status
    unique_id: washing_machine_status
    name: Washing Machine Status
    availability: "{{ has_value('input_select.washing_machine_status') }}"
    state: '{{ states(''input_select.washing_machine_status'') }}'
- sensor:
  - unit_of_measurement: W
    default_entity_id: sensor.kitchen_total_power_now
    unique_id: kitchen_total_power_now
    device_class: power
    state_class: measurement
    name: Power Now - Kitchen
    availability: >
      {{ has_value('sensor.dishwasher_current_consumption') and
         has_value('sensor.tumble_dryer_current_consumption') and
         has_value('sensor.washing_machine_current_consumption') }}
    state: >
      {{ (
        states('sensor.dishwasher_current_consumption') | float(0) +
        states('sensor.tumble_dryer_current_consumption') | float(0) +
        states('sensor.washing_machine_current_consumption') | float(0)
      ) | round(3) }}
- sensor:
  - unit_of_measurement: kWh
    default_entity_id: sensor.kitchen_total_power_today
    unique_id: kitchen_total_power_today
    device_class: energy
    state_class: total_increasing
    name: Power Today - Kitchen
    availability: >
      {{ has_value('sensor.dishwasher_today_s_consumption') and
         has_value('sensor.tumble_dryer_today_s_consumption') and
         has_value('sensor.washing_machine_today_s_consumption') }}
    state: >
      {{ (
        states('sensor.dishwasher_today_s_consumption') | float(0) +
        states('sensor.tumble_dryer_today_s_consumption') | float(0) +
        states('sensor.washing_machine_today_s_consumption') | float(0)
      ) | round(3) }}
- sensor:
  - unit_of_measurement: GBP
    default_entity_id: sensor.dishwasher_total_power_cost_today
    unique_id: dishwasher_total_power_cost_today
    device_class: monetary
    state_class: total
    name: Dishwasher Cost Today
    availability: >
      {{ has_value('sensor.electricity_unit_price') and
         has_value('sensor.dishwasher_today_s_consumption') }}
    state: >
      {{ (
        states('sensor.electricity_unit_price') | float(0) *
        states('sensor.dishwasher_today_s_consumption') | float(0)
      ) | round(2) }}
- sensor:
  - unit_of_measurement: GBP
    default_entity_id: sensor.tumble_dryer_total_power_cost_today
    unique_id: tumble_dryer_total_power_cost_today
    device_class: monetary
    state_class: total
    name: Tumble Dryer Cost Today
    availability: >
      {{ has_value('sensor.electricity_unit_price') and
         has_value('sensor.tumble_dryer_today_s_consumption') }}
    state: >
      {{ (
        states('sensor.electricity_unit_price') | float(0) *
        states('sensor.tumble_dryer_today_s_consumption') | float(0)
      ) | round(2) }}
- sensor:
  - unit_of_measurement: GBP
    default_entity_id: sensor.washing_machine_total_power_cost_today
    unique_id: washing_machine_total_power_cost_today
    device_class: monetary
    state_class: total
    name: Washing Machine Cost Today
    availability: >
      {{ has_value('sensor.electricity_unit_price') and
         has_value('sensor.washing_machine_today_s_consumption') }}
    state: >
      {{ (
        states('sensor.electricity_unit_price') | float(0) *
        states('sensor.washing_machine_today_s_consumption') | float(0)
      ) | round(2) }}
- sensor:
  - unit_of_measurement: GBP
    default_entity_id: sensor.kitchen_total_power_cost_today
    unique_id: kitchen_total_power_cost_today
    device_class: monetary
    state_class: total
    name: Power Cost Today - Kitchen
    availability: >
      {{ has_value('sensor.electricity_unit_price') and
         has_value('sensor.kitchen_total_power_today') }}
    state: >
      {{ (
        states('sensor.electricity_unit_price') | float(0) *
        states('sensor.kitchen_total_power_today') | float(0)
      ) | round(2) }}

sensor:
  - platform: history_stats
    name: Dishwasher uses today
    entity_id: sensor.dishwasher_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Dishwasher uses this week
    entity_id: sensor.dishwasher_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Dryer uses today
    entity_id: sensor.dryer_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Dryer uses this week
    entity_id: sensor.dryer_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Washing machine uses today
    entity_id: sensor.washing_machine_status
    type: count
    state: 'finished'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Washing machine uses this week
    entity_id: sensor.washing_machine_status
    type: count
    state: 'finished'
    start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
