##################################################
## Customize
##################################################
# homeassistant:
#   customize:

##################################################
## Groups
##################################################
group:
  adults_home:
    name: Adults at home
    entities:
      - person.june
      - person.martin
      - person.michelle
  children_home:
    name: Children at home
    entities:
      - person.morgan
      - person.fraser
  anyone_home:
    name: anyone at home
    entities:
      - person.june
      - person.martin
      - person.michelle
      - person.morgan
      - person.fraser

##################################################
## Components/Sensors
##################################################
input_boolean:
  guest_mode:
    name: Guest Mode

##################################################
## Automation
##################################################
automation:
  - alias: House occupied
    trigger: 
      platform: state
      entity_id: group.anyone_home
      to: 'home'
    condition:
      condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    action:
      - service: climate.set_preset_mode
        data_template:
          entity_id: climate.hallway_house
          preset_mode: none

  - alias: House unoccupied
    trigger: 
      platform: state
      entity_id: group.anyone_home
      from: 'home'
    condition:
      condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    action:
      - service: climate.set_preset_mode
        data_template:
          entity_id: climate.hallway_house
          preset_mode: eco
      - service: homeassistant.turn_on
        entity_id:
          - script.everyone_away

  - alias: Morgan away
    trigger: 
      platform: state
      entity_id: person.morgan
      from: 'home'
    condition:
      condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - script.morgan_away

  - alias: Morgan away window open
    trigger: 
      platform: state
      entity_id: person.morgan
      from: 'home'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
        - condition: state
          entity_id: binary_sensor.lumi_lumi_sensor_magnet_993d0303_on_off
          state: 'on'
    action:
      - service: notify.morgan
        data:
          title: "Home Assistant: ALERT!"
          message: "Bedroom Window Left Open"
      - service: notify.michelle
        data:
          title: "Home Assistant: ALERT!"
          message: "Morgans window has been left open"

  - alias: Fraser away
    trigger: 
      platform: state
      entity_id: person.fraser
      from: 'home'
    condition:
      condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - script.fraser_away

  - alias: House unoccupied things left open
    trigger: 
      platform: state
      entity_id: group.anyone_home
      from: 'home'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_5b337502_on_off # Front Door
              state: 'on'
            - condition: state
              entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_bc705302_on_off # Garage Door
              state: 'on'
            - condition: state
              entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_643f6703_on_off # Back Door
              state: 'on'
            - condition: state
              entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_10327502_on_off # Ironing Room window
              state: 'on'
            - condition: state
              entity_id: binary_sensor.lumi_lumi_sensor_magnet_993d0303_on_off # Morgan window
              state: 'on'
    action:
      - service: notify.martin
        data_template:
          title: "House Unoccupied - Things left open"
          message: "{{ states.binary_sensor.lumi_lumi_sensor_magnet_aq2_5b337502_on_off.attributes['friendly_name']}} [{{ states.binary_sensor.lumi_lumi_sensor_magnet_aq2_5b337502_on_off.state }}], 
                    {{ states.binary_sensor.lumi_lumi_sensor_magnet_aq2_bc705302_on_off.attributes['friendly_name']}} [{{ states.binary_sensor.lumi_lumi_sensor_magnet_aq2_bc705302_on_off.state }}], 
                    {{ states.binary_sensor.lumi_lumi_sensor_magnet_aq2_643f6703_on_off.attributes['friendly_name']}} [{{ states.binary_sensor.lumi_lumi_sensor_magnet_aq2_643f6703_on_off.state }}], 
                    {{ states.binary_sensor.lumi_lumi_sensor_magnet_aq2_10327502_on_off.attributes['friendly_name']}} [{{ states.binary_sensor.lumi_lumi_sensor_magnet_aq2_10327502_on_off.state }}], 
                    {{ states.binary_sensor.lumi_lumi_sensor_magnet_993d0303_on_off.attributes['friendly_name']}} [{{ states.binary_sensor.lumi_lumi_sensor_magnet_993d0303_on_off.state }}]"

##################################################
## Scripts
##################################################
script:
  morgan_away:
    alias: Morgan away
    sequence:
      - service: homeassistant.turn_off
        entity_id:
          - light.lwrf_morgan_main
          - group.morgans_strip_lights
  
  fraser_away:
    alias: Fraser away
    sequence:
      - service: homeassistant.turn_off
        entity_id:
          - group.frasers_room_lights
  
  everyone_away:
    alias: everyone_away
    sequence:
      - service: homeassistant.turn_off
        entity_id:
          - script.morgan_away
          - script.fraser_away
          - group.conservatory_lights
          - group.dining_room_lights
          - group.living_room_lights
          - switch.sonoff_garage_light

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - person.fraser
      - person.june
      - person.martin
      - person.michelle
      - person.morgan
      - group.adults_home
      - group.children_home
      - group.anyone_home
      - input_boolean.guest_mode

history:
  include:
    entities:
      - person.fraser
      - person.june
      - person.martin
      - person.michelle
      - person.morgan
      - group.adults_home
      - group.children_home
      - group.anyone_home
      - input_boolean.guest_mode
