##################################################
## Customize
##################################################
homeassistant:
  customize:
    media_player.living_room:
      friendly_name: "Living Room"
    media_player.kitchen:
      friendly_name: "Kitchen"
    media_player.conservatory:
      friendly_name: "Conservatory"
    media_player.master_bedroom:
      friendly_name: "Master Bedroom"
    media_player.bathroom:
      friendly_name: "Ensuite"

##################################################
## Scripts
##################################################
script:
  sonos_say:
    # Source: https://home-assistant.io/cookbook/sonos_say/
    alias: Sonos TTS script
    sequence:
      - service: sonos.snapshot
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: sonos.unjoin
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: media_player.volume_set
        data_template:
          entity_id: "{{ sonos_entity }}"
          volume_level: "{{ volume }}"
      # - service: tts.voicerss_say
      - service: tts.google_translate_say
        data_template:
          entity_id: "{{ sonos_entity }}"
          message: "{{ message }}"
      - delay: "{{ delay }}"
      - service: sonos.restore
        data_template:
          entity_id: "{{ sonos_entity }}"

  sonos_alarm:
    alias: Sonos Burglar Alarm Siren
    sequence:
      - service: sonos.snapshot
      - service: sonos.unjoin
      - service: media_player.volume_mute
        data_template:
          is_volume_muted: false
      - service: media_player.volume_set
        data_template:
          volume_level: "{{ volume }}"
      - service: media_player.play_media
        data_template:
          media_content_id: !secret siren_wav_url
          media_content_type: "audio/mp3"
      - delay: "{{ delay }}"
      - service: sonos.restore

##################################################
## Automation
##################################################
automation:
  - alias: Sonos TTS Test
    trigger:
      - platform: state
        entity_id: input_boolean.mytest
    action:
      - service: script.sonos_say
        data:
          sonos_entity: media_player.conservatory
          volume: 0.5
          message: "This is a test of Sonos Text to Speech"
          # Delay needs to be long enough to allow text to be read aloud
          delay: "00:00:05"

  - alias: Sonos Burglar Alarm
    trigger:
      - platform: state
        entity_id: input_boolean.mytest
    action:
      - service: script.sonos_alarm
        data:
          # Maximum Volume
          volume: 1.0
          # Duration before stopping and restoring state
          delay: "00:01:00"

  - alias: Sonos restore snapshot state
    trigger:
      - platform: state
        entity_id: input_boolean.mytest
    action:
      - service: sonos.restore