##################################################
## Components/Sensors
##################################################
sensor:
  - platform: template
    sensors:
      tesla_charging_status:
        value_template: "{{ states('input_select.tesla_charging_status') }}"
        friendly_name: "Tesla Charging Status"
        icon_template: "mdi:car-electric"

  - platform: template
    sensors:
      tesla_charging_cost_today:
        value_template: "{{ (states('input_number.energy_elec_unit') | float * states('sensor.tesla_charger_today_s_consumption') | float) | round(2) }}"
        unit_of_measurement: 'GBP'
        friendly_name: "Tesla Charging Cost Today"
        icon_template: "mdi:currency-gbp"
      tesla_changing_cost_this_month:
        value_template: "{{ (states('input_number.energy_elec_unit') | float * states('sensor.tesla_charger_this_month_s_consumption') | float) | round(2) }}"
        unit_of_measurement: 'GBP'
        friendly_name: "Tesla Charging Cost This Month"
        icon_template: "mdi:currency-gbp"

