##################################################
## Customize
##################################################
homeassistant:
  customize:
    binary_sensor.lumi_lumi_sensor_magnet_aq2_5b337502_on_off:
      icon: mdi:door
      friendly_name: "Front Door"
    sensor.lumi_lumi_sensor_magnet_aq2_5b337502_power:
      friendly_name: "Front Door - Battery"
    binary_sensor.lumi_lumi_sensor_magnet_aq2_643f6703_on_off:
      icon: mdi:door
      friendly_name: "Back Door"
    sensor.lumi_lumi_sensor_magnet_aq2_643f6703_power:
      friendly_name: "Back Door - Battery"
    binary_sensor.lumi_lumi_sensor_magnet_aq2_bc705302_on_off:
      icon: mdi:door
      friendly_name: "Garage Interior Door"
    sensor.lumi_lumi_sensor_magnet_aq2_bc705302_power:
      friendly_name: "Garage Interior Door - Battery"
    binary_sensor.lumi_lumi_sensor_magnet_aq2_10327502_on_off:
      icon: mdi:window-open
      friendly_name: "Ironing Room - Window"
    sensor.lumi_lumi_sensor_magnet_aq2_10327502_power:
      friendly_name: "Ironing Room - Windows - Battery"
    binary_sensor.lumi_lumi_sensor_magnet_993d0303_on_off:
      icon: mdi:window-open
      friendly_name: "Morgan - Window"
    sensor.lumi_lumi_sensor_magnet_993d0303_power:
      friendly_name: "Morgan - Windows - Battery"
    sensor.lumi_lumi_sens_ca8a3702_humidity:
      icon: mdi:water-percent
      friendly_name: "ZigBee TH1 - Humidty"
    sensor.lumi_lumi_sens_ca8a3702_temperature:
      friendly_name: "ZigBee TH1 - Temperature"
    sensor.lumi_lumi_sens_ca8a3702_power:
      friendly_name: "ZigBee TH1 - Battery"


##################################################
## Automation
##################################################

# If back door open set heating mode to Eco, set to heat when closed.
# This originally stored the state and restored it, however this seemed unrealible, maybe a Nest API rate limit issue.
# To reduce the chance of hitting Nest API rate limits, door needs to be in open for 2 mins before a change made.
automation:
  - alias: Door Open - Set heating mode to eco
    trigger:
      - platform: state
        entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_643f6703_on_off  # Back door
        to: 'on'
        for:
          minutes: 2
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.hallway_house
          operation_mode: 'eco'
  
  - alias: Door Closed - Reset heating mode
    trigger:
      - platform: state
        entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_643f6703_on_off # Back door
        to: 'off'
    action:
      - service: climate.set_operation_mode
        data_template:
          entity_id: climate.hallway_house
          operation_mode: 'heat'

##################################################
## Recorder/History
##################################################
recorder:
  include:
    entities:
      - sensor.lumi_lumi_sens_ca8a3702_humidity # Humidity
      - sensor.lumi_lumi_sens_ca8a3702_temperature # Temperature
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_5b337502_on_off # Magnetic Front Door
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_643f6703_on_off # Magnetic Back Door
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_bc705302_on_off # Magnetic Garage Interior Door
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_10327502_on_off # Magnetic Ironing Room Window
      - binary_sensor.lumi_lumi_sensor_magnet_993d0303_on_off # Magnetic Morgan Window

history:
  include:
    entities:
      - sensor.lumi_lumi_sens_ca8a3702_humidity # Humidity
      - sensor.lumi_lumi_sens_ca8a3702_temperature # Temperature
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_5b337502_on_off # Magnetic Front Door
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_643f6703_on_off # Magnetic Back Door
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_bc705302_on_off # Magnetic Garage Interior Door
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_10327502_on_off # Magnetic Ironing Room Window
      - binary_sensor.lumi_lumi_sensor_magnet_993d0303_on_off # Magnetic Morgan Window
